# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 09:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0003_auto_20170607_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='comics',
        ),
        migrations.RemoveField(
            model_name='comic',
            name='characters',
        ),
        migrations.RemoveField(
            model_name='userfollows',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='userfollows',
            name='characters',
        ),
        migrations.RemoveField(
            model_name='userfollows',
            name='comics',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Character',
        ),
        migrations.DeleteModel(
            name='Comic',
        ),
        migrations.DeleteModel(
            name='UserFollows',
        ),
    ]
