# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comics', '0006_auto_20170608_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.CharField(max_length=50, primary_key='true', serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('town', models.CharField(max_length=1000)),
                ('country', models.CharField(max_length=1000)),
                ('gender', models.CharField(max_length=1000)),
                ('alias', models.CharField(max_length=1000)),
                ('birth_date', models.CharField(max_length=1000)),
                ('biography', models.CharField(max_length=10000)),
                ('image', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='AuthorFollows',
            fields=[
                ('follows_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=50)),
                ('follows', models.DateTimeField(auto_now=True)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='comics.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('character_id', models.CharField(max_length=50, primary_key='true', serialize=False)),
                ('super_name', models.CharField(max_length=1000)),
                ('real_name', models.CharField(max_length=1000)),
                ('aliases', models.CharField(max_length=1000)),
                ('publisher', models.CharField(max_length=1000)),
                ('gender', models.CharField(max_length=1000)),
                ('character_type', models.CharField(max_length=1000)),
                ('powers', models.CharField(max_length=1000)),
                ('image', models.CharField(max_length=1000)),
                ('origin', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterFollows',
            fields=[
                ('follows_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=50)),
                ('follows', models.DateTimeField(auto_now=True)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='comics.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('comic_id', models.CharField(max_length=50, primary_key='true', serialize=False)),
                ('issue_number', models.IntegerField()),
                ('title', models.CharField(max_length=1000)),
                ('image', models.CharField(max_length=1000)),
                ('store_date', models.CharField(max_length=1000)),
                ('synopsis', models.CharField(max_length=10000)),
                ('characters', models.ManyToManyField(to='comics.Character', verbose_name='list of characters')),
            ],
        ),
        migrations.CreateModel(
            name='ComicFollows',
            fields=[
                ('follows_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=50)),
                ('follows', models.DateTimeField(auto_now=True)),
                ('comic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='comics.Comic')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='comics',
            field=models.ManyToManyField(to='comics.Comic', verbose_name='list of comics'),
        ),
    ]
