# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0007_auto_20170608_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorfollows',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comics.Author'),
        ),
        migrations.AlterField(
            model_name='characterfollows',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comics.Character'),
        ),
        migrations.AlterField(
            model_name='comicfollows',
            name='comic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comics.Comic'),
        ),
    ]
