# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-10 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0008_auto_20170608_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='comics',
        ),
        migrations.RemoveField(
            model_name='comic',
            name='characters',
        ),
        migrations.AlterField(
            model_name='comic',
            name='issue_number',
            field=models.CharField(max_length=100),
        ),
    ]
